const UI = {
  //  Filter
  LOADING: 'Loading',
  MORE: 'more',
  SHOW: 'Show',
  RESET: 'Reset',
  FILTER: 'Filter',
  FILTER_APPLIED: '(Filters applied)',
  SHOWING_RESULT_FOR: 'Showing result for',
  SHOWING_RESULT_FOR_MOBILE: 'Results for',
  JOBS: 'Jobs',
  REMARKS: 'Remarks',
  COOKIES_POLICY: 'Cookie policy',
  EMPLOYER_PROFILE: 'Employer profile',
  COOKIES_MSG:
    'We use cookies to ensure that you get the best experience on our website. By continuing to use this site, you give your consent to our',
  DEGREE: 'Degree',
  APPLICABLE_WHEN_PROFILE_IS_UPDATED: 'Applicable when profile is updated',
  VALIDITY: 'Validity',
  NEXT_ATTEMPT: 'Next Attempt',
  MATCHING: 'Matches',
  SEARCH_ON: 'Searched',
  RECENT_SEARCHES: 'Recent Searches',
  CONTACT_PERSON: 'Contact person',
  APPLIED_JOBS: 'Applied Jobs',
  AUTO_APPLIED_BY_EMPLOYER: 'Auto Applied By Employer',
  CANDIDATES_FOR_JOB: 'Candidates for Job',
  MARKED: 'Marked ',
  PAGE_NOT_FOUND:
    'This space is blank right now, but every story began with a blank page.', // TBD - 'Page not Found...',
  PAGE_NOT_FOUND1:
    'Nothing here yet, but every painting was once a blank canvas', // TBD - there can be multiple such options to be shown to the user...'Page not Found...',
  //  Guidelines
  START: 'Start',
  GENERAL_INSTRUCTION: 'General Instructions',
  TERMS_CONDITIONS: 'Terms & Conditions',
  GUIDELINE_INSTRACTION: 'I have read all the instructions and agree to the',
  ASSESSMENT_INSTRUCTION: 'Assessment Instructions',

  //  Assessment
  NOT_PASSED: 'Not passed',
  NO_RESULT: 'No result',
  ATTEMPTS_HISTORY: 'Attempts History',
  COMPLETED: 'Completed',
  COMPLETE: 'Complete',
  FOUND: 'found',
  AVAILABLE: 'Available',
  ANY: 'Any',
  REMANING_TIME: 'Remaining time',
  TIME_SPENT_ON_THIS_QUESTION: 'Time spent on this question',
  READ_TO_INSTRUCTIONS: 'Read instructions',
  END_TEST: 'End Test',
  SHOW_TO_EMPLOYER: 'Showcase this badge', // TBD 'Show to employer'
  YOUR_SKILL_RATING: 'Your current skill level is',
  SUBMIT_SUCCESSFUL: 'Your Assessment has been submitted successfully',
  YOUR_SCORE_IS_VERY_LESS:
    'You made a good attempt, but a little more effort will help you improve your rating. An improved rating will increase your chances of getting hired. We suggest you study the relevant topics thoroughly and re-assess yourself after 30 days.', // 'Your score is very low and he is not even in the category of Beginner, You have not crossed the cut-off set by us, so your ratings will not be visible to the employers. Please give assessment again after 30 days.'
  ASSESSMENT: 'Assessment',
  ASSESSMENTS: 'Assessments',
  SETTING: 'Settings',
  OFFERS: 'My Offers',
  SAVE_SUBMIT: 'Save & Submit',
  SAVE_NEXT: 'Save & Next',
  SEC: 'sec',
  APPROX_TIME: 'Approximate time you should spend on this question',
  PLEASE_SELECT_AN_ANY_OPTION: 'Please select an option.',
  RE_ATTEMPT: 'Re-Attempt',
  NEED_IMPROVEMENT: 'Needs improvement',
  SKILL_RATING: 'Rating',
  ERROR: 'Error',
  START_TEST: ' Start Test',
  NUMBER_OF_QUESTIONS: 'Question Number', // As the context is showing question # out of total number so Number of Question is incorrect
  QUESTIONS: 'Questions',
  TIME: 'Time',
  MIN: 'min',
  TOTAL_ASSESSMENT_FOUND: 'Total assessments found',
  LOGIN_REQD_ASSESSMENT: '* Login is required to take assessments',
  SKILL_TYPE: 'Skill Type',
  AVAILABLE_ASSESSMENT: 'Available Assessment',
  GREAT_START:
    'Great start, but time has run out. You won’t be able to attempt the rest of the assessment this time. Please re-assess yourself after 30 days.', // 'Great start, but your time is up so are not able to answer remaing questions.',
  GENERATE_REPORT: 'Generate Report',
  RETRY_AFTER_30_DAYS: 'Retry after 30 days', // TBD: Need to remove hardcoding
  CLOSE: 'Close',
  YOU_ARE_GOING_TO_SUBMIT_ASSESSMENT:
    'You are going to submit this assessment, Once submitted your result will be generated.', // TBD - Context not clear… It requires changes

  ASSESSMENT_CONFIRM: 'Do you want to take the assessment?',
  DO_YOU_WANT_TO_CONFIRM: 'Do you want to confirm?',
  HOLD_ON: 'Hold on.',
  FLIP_QUESTIONS: 'Flipped questions',
  QUESTIONS_REMAINING: 'questions are remaining.',
  SURE_SUBMIT_ASSESSMENT: 'Do you want to submit this assessment?',
  SUBMIT_ASSESSMENT: 'Submit Assessment',
  ASSESSMENT_TIMED_OUT: 'Assessment timed out',
  YES: 'Yes',
  NO: 'No',
  END_ASSESSMENT_TITLE: 'End Assessment',
  SURE_END_ASSESSMENT: 'Do you want to end this assessment?',
  SURE_DELETE_ACCOUNT: `Deleting the account will remove all your information present in your system (in the form of cookies, browser storage) as well as all your information present in our database. You won't be able to login with this registered email ID. Do you want to Delete this account?`,
  FLIP_THE_QUESTIONS: 'Flip the Question',
  FLIP_THIS_QUESTIONS: 'Flip this Question',
  SURE_FLIP_QUESTION: 'Do you want to flip this question?',
  //  Summary List
  PAGE: 'Page',
  SHOWING: 'Showing',
  RESULTS: 'Results',
  SORT_BY: 'Sort by',
  OF: 'of',
  RELEVANCE: 'Relevance',

  //  Posted Jobs
  MATCHING_CANDIDATES: 'Matching Candidates',
  APPLIED_CANDIDATES: 'Applicants',
  PUBLISHED: 'Published',
  STATUS: 'Status',
  UPDATED: 'Updated',
  PRE_REQUISITES: 'Pre-Requisites',

  //  Transaction Status
  BANK_TRANSACTION_ID: 'Bank transaction Id',
  GATEWAY_TRANSACTION_ID: 'Gateway transaction Id',
  ORDERID: 'Order ID',
  TRANSACTION_TIME: 'Transaction time',
  AMOUNT: 'Amount',
  MESSAGE: 'Message',
  OK: 'OK',

  //  Buy Credit Points
  BUY_CREDIT: 'Buy Credit Points',
  ENTER_AMOUNT: 'Enter Amount',
  POINTS_WILL_BE_ADDED: 'Equivalent to points',
  APPLY_DISCOUNT_CODE: 'Apply Discount Code',
  PLACEHOLDER_DISCOUNT_CODE: 'Enter discount code',
  OPTIONAL: '(optional)',
  BUTTON_NEXT: 'Next',

  // My Offers
  REFER_EMPLOYERS: 'Referral Offers for Employers:',
  PROMOTION_CANDIDATES: 'For Candidates:',
  REFER_TO_CANDIDATES: 'Refer a Candidate:',
  REFER_TO_EMPLOYER: 'Refer an Employer:',
  PROMOTION_EMPLOYER: 'For Employers:',
  REFER_CANDIDATES: 'Referral Offers for Candidates:',
  REFERRAL_LINK: 'Generate Referral Link',
  REFER_SUCCESS: 'Referral Link Copied to clipboard!',

  //  Point Summary
  CREDIT_POINTS: 'Credit Points',
  PROFILE: 'Profile',
  POINTS: 'Points',
  AVAILABLE_POINTS: 'Available Points',
  BUY_POINTS: 'Buy Points',
  FREE_POINTS: 'Free Points',
  REDEEM_FREE_POINTS: 'Redeem coupon',
  FREE_CODE_PLACEHOLDER: 'Enter coupon code',
  APPLY_BUTTON: 'Apply',
  COUPON_CODE_APPLIED: 'Coupon applied successfully',

  //  Price Details
  PAYMENT_STATUS: 'Payment Status',
  PRICE_DETAILS: 'Payment Details',
  TOTAL: 'Total',
  TAX: 'GST',
  TOTAL_PAYABLE_AMOUNT: 'Total Payable Amount',
  BACK_BUTTON: 'Back',
  MAKE_PAYMENT: 'Make Payment',
  FAILED: 'Payment Failed',
  SUCCESSFUL: 'Payment Successful',
  TRY_AGAIN: 'Try Again',

  //  Transaction History
  VIEW_TRANSACTION_HISTORY: 'View Transaction History',
  TRANSACTION_TYPE: 'Transaction Type',
  CREDIT: 'Credit',
  DEBIT: 'Debit',
  CASHBACK: 'Cashback',
  DETAILS: 'Details',
  POSTED_JOB: 'Posted Jobs',
  SELECT_OPTION: '--select--',
  PLACEHOLDER_CITY: 'Select city',
  MINIMUM_SALARY: 'Minimum',
  MAXMIMUM_SALARY: 'Maximum',
  MINMAXERROR: 'Minimum must be smaller than or equals to Maximum',
  ANY_SALARY: 'Open for discussion',
  PER_ANNUN: ' PA',
  //  Candidate Steps
  LOCATION: 'Location',
  DESIRED: 'Desired',
  REQUIRES: 'Requires',
  FRESHER: 'Fresher',
  ANY_LOCATION: 'Any Location',
  YEAR: 'year',
  DESIRED_LOCATION: 'Desired Location',
  PERSONAL_INFORMATION: 'Personal Information',
  DESIRED_JOBS: 'Desired Jobs',
  SKILLS: 'Skills',
  EDUCATION: 'Education',
  JOB_HISTORY: 'Job History',
  BREAK: 'Break',
  TOOLS: 'Tools',
  TOOL: 'Tool',
  CERTIFICATIONS: 'Certifications',
  OTHER: 'Other',
  SCHOOLING: 'Schooling',
  TO_UNLOCK: 'to Unlock',
  DOWNLOAD_RESUME: 'Download Resume',
  RESUME_NOT_AVAILABLE: 'Resume not available',
  RESUME_AVAILABLE: 'Resume available after Unlock',
  DELETE_RESUME: 'Delete Resume',
  DOWNLOAD_ID_PROOF: 'Download ID Proof',
  DOWNLOAD_ICARD_PROOF: 'Download Company ID Proof',
  DELETE_ID_PROOF: 'Delete ID Proof',
  DELETE_ICARD_PROOF: 'Delete Company ID Proof',
  //  Company profile
  COMPANY_DETAILS: 'Company details',
  CONTACT_DETAILS: 'Contact details',
  EMPLOYER_JOBS: 'Employer jobs',
  OTHER_DETAILS: 'Other details',
  //  Post jobs
  ALT_LESS_RATING: 'Less rating scored in assessment on Align My Career',
  JOB_DETAILS: 'Job Details',
  SKILLS_AND_EXPERIENCE: 'Skills and Experience',
  RELEVANT_SKILLS: 'Add most relevant skills first',
  FIRST_TWO_OPTION:
    'Match the first 2 mentioned skills with the Candidates’ skill set for more results (recommended)',
  ALL_SKILLS_OPTION: 'Match all the above skills',
  ALL_SKILLS_OPTION_NOTE:
    'Note: This option will match candidates having all the mentioned skills, so the number of results might be very less, therefore not recommended.',
  POSTED: 'Posted',
  RESPONSE_AWAITED: '(Response awaited)',
  FULL_NAME: 'Full name',
  EMAIL: 'Email',
  MOBILE: 'Mobile',
  MOBILE_NUMBER: 'Mobile number',
  DATE_OF_BIRTH: 'Date of birth',
  GENDER: 'Gender',
  PASSPORT_NUMBER: 'Passport number',
  UPI: 'UPI ID',
  CITY: 'City',
  ADDRESS: 'Address',
  ENTER_YOUR_ADDRESS: 'Enter your address',
  ABOUT: 'About',
  PLACEHOLDER_ABOUT: 'Write a short introduction about yourself',
  RESUME: 'Resume',
  ID_PROOF: 'Photo Identity proof',
  ICARD_PROOF: 'Company Identity proof',
  OPEN_TO_WORK_AT_ANY_LOCATION: 'Open to work at any location',
  JOB_LOCATIONS: 'Job location(s)',
  JOB_LOCATION: 'Current Job location',
  EXPERIENCE: 'Experience',
  IN_MONTHS: 'in months',
  JOB_TYPE: 'Job type',
  WORK_LOCATION: 'Mode of Work',
  NEGOTIABLE: 'Negotiable',
  ARE_YOU_A_FRESHER: 'I am a fresher',
  DESIRED_SALARY: 'Desired Salary',
  WORK_EXPERIENCE_IN_YEAR: 'Work experience in year(s)',
  SHIFT: 'Shift',
  WHEN_CAN_YOU_JOIN: 'When can you join',
  WILLINGNESS_TO_RELOCATE: 'Willingness to relocate',
  EXPECTED_SALARY: 'Expected Salary',
  RATING: 'Rating',
  WHERE: 'Where',
  LAST_USED: 'Last used',
  TOOLS_PLACEHOLDER: 'Tool e.g. Eclipse, UML, Excel, Gitlab, Postman etc',
  COLLEGE_UNIVERSITY: 'College/University',
  COLLEGE: 'College',
  COURSE: 'Course',
  FROM: 'From',
  DATE_PLACEHOLDER: '01/01/2022',
  TO: 'To',
  AT_PRESENT: 'Ongoing',
  PERCENTAGE: 'Percentage (%)',
  PERCENTAGE_NAME: 'Percentage',
  PERCENT_SIGN: '%',
  UPLOADED_ON: 'Uploaded on ',
  REMOVE: 'Remove',
  REMOVE_PHOTO: 'Remove Photo',
  PHOTO: 'Photo',
  UPLOAD: 'Upload',
  SUPPORTED_FORMATS: 'Supported formats: ',
  CGPA: 'CGPA',
  WORK_EXPERIENCE: 'Employment',
  JOB_TITLE: 'Job title',
  TITLE: 'Title',
  COMPANY_NAME: 'Company Name',
  COMPANY: 'Company',
  CTC: 'CTC (PA)',
  PA: 'PA',
  CTC_PLACEHOLDER: 'CTC',
  ROLES_RESPONBILITIES: 'Roles/Responsibilities',
  REASON: 'Reason',
  VISIBILITY: 'Visible to the employer',
  NAME: 'Name',
  DESCRIPTION: 'Description',
  DATE: 'Date',
  VALIDITY_IN_MONTHS: 'Validity in months',
  ACHIEVEMENTS: 'Achievements',
  ACADEMIC_EXCELLENCE: 'Academic excellence',
  OPEN_SOURCE_COMMUNITY_CONTRIBUTION: 'Open source community contribution',
  PROJECTS: 'Projects',
  HOBBIES: 'Hobbies',
  PATENTS: 'Patents',
  LANGUAGE: 'Language',
  PROFILE_LINK: 'Profile link',
  LINKEDIN_LINK: 'Linkedin link',
  GITHUB_LINK: 'GitHub link',
  ONLINE_PROFILE_URL: 'Online profile URL',
  LINKEDIN: 'LinkedIn',
  GITHUB: 'GitHub',
  SCHOOL_NAME: 'Name of School',
  CLASS_NAME: 'Class',
  BOARD: 'Board',
  SAVE_AS_DRAFT: 'Save As Draft',
  POST_JOB: 'Post Job',
  // University
  DASHBOARD: 'Dashboard',
  CAPITAL_YEAR: 'Year',
  REGISTRATION_DATE: 'Registration Date',
  ASSESSMENT_DATE: 'Assessment Date',
  OFFERED_DATE: 'Offered Date',
  HIRED_DATE: 'Hired Date',
  TOTAL_CANDIDATES: 'Total Candidates',
  TOTAL_ASSESSED_CANDIDATES: 'Total Assessed Candidates',
  TOTAL_NON_ASSESSED_CANDIDATES: 'Total Non-Assessed Candidates',
  REGISTERED_CANDIDATES: 'Registered Candidates',
  ASSESSED_CANDIDATES: 'Assessed Candidates',
  OFFERED_CANDIDATES: 'Offered Candidates',
  HIRED_CANDIDATES: 'Hired Candidates',
  TODAY: 'Today',
  YESTERDAY: 'Yesterday',
  THIS_WEEK: 'This week',
  LAST_WEEK: 'Last week',
  THIS_MONTH: 'This month',
  LAST_MONTH: 'Last month',
  CUSTOM: 'Custom',

  CANDIDATE_COMPLETE_PROFILE_AND_INCREASE:
    'Complete profile and increase chances of getting hired',
  EMPLOYER_COMPLETE_PROFILE_AND_INCREASE:
    'Complete profile to hire the best talent instantly',

  POST_JOBS_PROFILE_MSG: 'Post jobs for enhanced visibility to the best talent',
  EXPIRE: 'Expires on',
  BACK: 'Back',
  NEXT: 'Next',
  POINT: 'credit point', // TBD - assuming that it will be shown as part of “Requires <1> point”
  JOB_DESCRIPTION: 'Job description',
  MINIMUM_QUALIFICATION: 'Minimum qualification',
  SALARY: 'Salary',
  OVERALL_EXPERIENCE: 'Overall experience',
  SKILLS_EXPERIENCE: 'Skills Experience',
  SKILL: 'Skill',
  NUMBER_OF_OPENINGS: 'Number of opening(s)',
  NUMBER_OF_OPENING: 'Number of opening',
  ALWAYS_HIRING: 'Always hiring',
  START_DATE: 'Start date',
  JOB_DEADLINE: 'Job deadline',
  JOB_EXPIRES_ON: 'Job expires on',
  PAY_BENEFITS: 'Pay benefits',
  OTHER_BENEFITS: 'Other benefits',
  UPDATE_PROFILE: 'Update Profile',
  SHOW_PREVIEW: 'Show Preview',
  SHOW_DETAILS: 'Show Details',
  TIMELINE: 'Timeline',
  SHOW_TIMELINE: 'Show Timeline',
  YOUR_PROFILE_UPDATED: 'Your profile was updated',
  COMPANY_PROFILE: 'Company profile',
  LOGO: 'Logo',
  COMPANY_EMAIL_ID: 'Company email ID',
  COMPANY_TAGLINE: 'Company tagline',
  COMPANY_BRIEF: 'Company brief',
  GST_REGISTERED: 'Are you GST registered?',
  GSTIN: 'GSTIN',
  GSTSTATE: 'GST State',
  FOUNDED_ON: 'Founded in',
  CONTACT_NAME: 'Contact person',
  CONTACT_NUMBER: 'Contact number',
  WEBSITE: 'Website',
  COMPANY_SIZE: "Company's headcount",
  COMPANY_STAGE: 'Company stage',
  FUNDING: 'Funding status',
  ENGINEERS_SIZE: "Engineers' headcount",
  TECHNOLOGY_STACK: 'Technology stack',
  HOW_DID_YOU_HEAR_ABOUT_US: 'How did you hear about us?',
  PLEASE_MENTION_HERE: 'Please mention here',
  FACEBOOK: 'Facebook',
  FACEBOOK_LINK: 'Facebook link',
  TWITTER: 'Twitter',
  TWITTER_LINK: 'Twitter link',
  INSTAGRAM: 'Instagram',
  INSTAGRAM_LINK: 'Instagram link',
  ENTER_OPENING: 'Enter opening(s)',
  GST_NO: 'GST No',
  SELECT_THE_MONTH_YEAR: 'Select the month-year',
  COMPANY_ADDRESS: 'Company address',
  WWW_EXAMPLE_COM: 'www.example.com',
  HEAROTHERS: 'From where did you hear about us',
  ENTER_A_REASON: 'Enter a reason',
  IN_MONTH: 'In month(s)',
  ENTER: 'Enter %',
  ENTER_CGPA: 'Enter CGPA',
  SEARCH_CITY: 'Search City',
  ENTER_DESIRED_SALARY: 'Enter Desired salary',
  IN_YEAR: 'In year(s)',
  PLEASE_SELECT_CORRECT_DATES: 'please select correct dates',
  ADD: 'Add',
  UPDATE: 'Update',
  ALT_BLUETICK: 'Assessments verified by Align My Career',
  BLUETICK_TEXT: 'AMC Verified',
  SELFRATED_TEXT: 'Self Rated',
  ALT_DELETE_ICON: 'Delete icon',
  ALT_CONGRATULATIONS:
    'Congratulations on clearing the Assessment on Align My Career',
  ALT_CANDIDATE_PROFILE: 'Candidate Picture',
  ALT_BADGE:
    'Technical, Development Tools, Soft Skills badges for clearing assessment on Align My Career',
  EARNED_BADGES: 'Earned Badges',
  GIVE_YOUR_ASSESSMENTS_AND_GET_BADGES: 'Take assessment and earn badges',
  ALT_EMPLOYER_LOGO: 'Company Logo',
  ALT_OTHER_PAGES: 'Other Pages',
  CHANGE: 'Change',
  DOCX_PDF_FILE_STR: 'docx, pdf, upto 1 MB',
  PNG_JPG_FILE_STR: 'png, jpg, jpeg, upto 100 KB',
  JOB_UPDATED_SUCCESSFULLY: 'Job Updated Successfully',
  RESUME_PAGES: 'Recommendation: 1-2 pages',

  PASSWORD_SENT_SUCCESSFULLY: 'Password Sent Successfully',
  PASSWORD_RESET_LINK_SENT_SUCCESSFULLY:
    'Password reset link sent successfully',
  LOGIN: 'Login',
  LOGOUT: 'Logout',
  PASSWORD: 'Password',
  FORGOT_PASSWORD: 'Forgot Password?',
  NEW_TO_COMPANY_IN: 'New to AlignMyCareer?',
  REGISTER_FOR_FREE: 'Register for Free',
  ENTER_PASSWORD: 'Enter password',
  FORGOT_PASSWORD_: 'Forgot Password',
  ENTER_YOUR_REGISTERED_EMAIL: 'Enter your registered email ID',
  SEND: 'Send',
  CHANGE_PASSWORD: 'Change Password',
  NEW_PASSWORD: 'New Password',
  ENTER_NEW_PASSWORD: 'Enter new password',
  SUBMIT: 'Submit',
  REGISTER: 'Register',
  FULL_NAME_COMPANY_NAME: 'Full name / Company name',
  ENTER_EMAIL: 'Enter email',
  PHONE_NUMBER: 'Phone number',
  ENTER_PHONE_NUMBER: 'Enter phone number',
  ROLE: 'Role',
  ROLE_PLACEHOLDER: 'HR Manager, Project Manager, CEO etc',
  USER_AGREEMENT: 'User Agreement',
  PRIVACY_POLICY: 'Privacy Policy',
  AND: 'and',
  TERM_AND_CONDITIONS: 'Terms & Conditions.',
  ALREADY_ON_COMPANY_IN: 'Already on AlignMyCareer?',
  BY_CLICKING_AGREE_JOIN_YOU_AGREE_TO_THE_COMPANY_IN:
    'By clicking Register, you agree to our', //  TBD
  CONFIRM_TOKEN_REDIRECT_PAGE: 'Confirm Token Redirect Page',
  INVALID_REGISTRATION_TOKEN: 'Invalid Registration token',
  RESEND_TOKEN: 'Resend Token',
  YOUR_OLD_TOKEN:
    'Your old Token has expired, please check your email for the new token link',
  OLD_PASSWORD: 'Old Password',
  ENTER_OLD_PASSWORD: 'Enter old password',
  RESEND_EMAIL: 'Resend Email',
  ENTER_YOUR_REGISTER_EMAIL: 'Enter your registered email ID',
  PASSWORD_SEND_SUCCESSFULLY: 'Password sent Successfully',
  PLEASE_CHECK_REGISTERED_EMAIL_ADDRESS: 'Please check your email',
  RESEND_RESET_PASSWORD_LINK: 'Resend reset password link',
  CONFIRM_EMAIL_SUCCESSFULL: 'Email confirmation successful',
  YOUR_EMAIL_ID_IS_REGISTERD: 'Your email registered successfully',
  NOW_CLICK_GOING_TO_LOGIN_SECTION: 'Click to',
  PLEASE_VERIFY_YOUR_EMAIL: 'Please verify your email',
  ONCE_YOU_VERIFY_YOUR_EMAIL_ADDRESS:
    'After verification of email, you are all set to explore',
  RESEND_REGISTRATION_MAIL_SUCCESSFUL: 'Resend Registration email successful',
  DIDNT_RECEIVE_AN_EMAIL: "Didn't receive an email?",
  UNSUBSCRIBE_MSG: 'You have been unsubscribed from this notification.',
  UNSUBSCRIBE_LINK: ` to manage your notification's settings.`,
  UNSUBSCRIBE_ERROR:
    'An error occured while unsubscribing. Please try again later.',
  HERE: 'here',
  CLICK: 'Click ',
  //  Feedback Form
  FEEDBACK_FORM: 'Contact Us/Feedback form',
  COMMENTS: 'Comments',
  COMMENTS_PLACEHOLDER: 'Enter your comments',

  //  Login

  //  My candidates
  ALL: 'All',
  AVAILABILITY: 'Availability',
  //  candidate View Components
  FROM_TO: 'From-to',
  ROLES: 'Roles',

  // Banners Page && Notifications Page
  NOTIFICATIONS: 'Notifications',
  NO_NOTIFICATIONS: 'No New Notifications for you!!!',
  MANAGE_NOTIFICATIONS: 'Manage your Notifications',
  VIEW_SETTINGS: 'View Settings',

  MONTH: 'month',
  DAY: 'day',
  MY_ASSESSMENT: 'My Assessments',
  MY_COMPANY_NAME: 'AlignMyCareer',
  ALL_RIGHT_RESERVED: 'All rights reserved',
  //  Header Navbar
  FIND_TALENT: 'Find Talent',
  FIND_JOBS: 'Find Jobs',
  MY_CANDIDATES: 'My Candidates',
  MY_JOBS: 'My Jobs',
  MY_PROFILE_ACTIVITY: 'My Profile Activity',
  //  Home page
  SEARCH: 'Search',
  REMARK: 'Remark',
  REMARK_PLACEHOLDER: 'Enter the candidate remark',
  // Find Jobs Home Page
  PROFILE_COMPLETED: 'Profile completed',
  PROFILE_APPEARANCE: 'Profile Appearance',
  LAST_30_DAYS: '(last 30 days)',
  PROFILE_APPEARED: 'Your Profile Appeared in',
  JOB_COUNT_PERFORMANCE: 'Job Stats',
  MATCHING_JOBS: 'Matching Jobs',
  SEARCHES_APPEARANCES: 'Search Appearances',
  TOTAL_ASSESSMENT: 'Total Assessments',
  PROFILE_VIEWS: 'Profile Views',
  SHORTLISTED: 'Shortlisted',
  CANDIDATE_INTERACTIONS: 'Candidate Stats',
  JOB_OFFERED: 'Job Offered',
  ACCEPTED: 'Offers Accepted',
  REJECTED: 'Offers Rejected',
  HIRED: 'Hired',
  AUTO_APPLIED: 'Auto-Applied Jobs',
  PROFILE_PERFORMANCE: 'Profile Performance',
  UNLOCKS: 'Unlocks',
  SHORTISTS: 'Shortlists',
  INTERVIEWS: 'Interviews',

  //  Footer
  JOB_SEEKER: 'Job Seeker',
  EMPLOYER: 'Employer',
  SOCIAL: 'Social',
  FIND_JOB: 'Find Job',
  TOKEN_NOT_VALID: 'Oops! Token is not valid',
  EXPIRED_TOKEN: 'Oops! Token is expired',
  FEEDBACK: 'Feedback',
  GENERATE_NEW_TOKEN: 'Generate new Token',
  OFFER_ERROR: `Couldn't load the offers, try again later`,

  // Password Reset Forgot Password

  PASSWORD_RESET_ATTEMPTS_EXCEEDED: 'Password reset attempts exceeded',
  USER_NOT_FOUND: 'User not Found',
  REMOVE_LOGO: 'Remove Logo',
  NO_MATCHING_RESULT_FOUND: 'No Matching Result Found...',
  CHANGE_YOUR_PREFERENCES: 'Change your search criteria to get more results.',
  NO_RESULT_FOUND: 'No result found',

  // For badges table

  EXPERT: 'Expert',
  PROFICIENT: 'Proficient',
  INTERMEDIATE: 'Intermediate',
  BEGINNER: 'Beginner',

  // Setting page
  SETTING_HEADING: 'Settings',
  SETTING_UPDATE: 'Change and update the settings',
  NOTIFICATIONS_SETTINGS: 'Notification Settings',
  BASIC_SETTING: 'Basic Settings',
  AUTO_APPLY: 'Auto Apply',
  AUTO_APPLY_DESCRIPTION: `Candidates have to make themselves "Available" by selecting this flag. This flag is automatically set to false after 30 days. This will allow only the interested candidates to appear in the employer's search`,
  SETTING_PASSWORD: 'Password',
  SETTING_CHANGE_PASSWORD: 'Change Password',
  SETTING_DELETE: 'Delete Account',
  SETTING_DELETE_MY_ACCOUNT: 'Delete My Account',
  MAIL_RECIPIENTS: 'Mail Recipients',
  MAIL_RECIPIENTS_DESCRIPTION:
    'Weekly updates on candidate reports will be sent to these email addresses.',
  MAX_EMAILS: 'Maximum 5 email addresses allowed',
  EMAILS_ENTER: 'Press Enter to add email',
  INVALID_EMAIL_ADDRESS: 'Invalid email address ',
  GLOBAL_NOTIFICATION_TITLE: 'Global Notification Settings',
  GLOBAL_NOTIFICATION_MSG:
    'Enable/Disable these settings to turn on/off all the notification types quickly.',
  LOCAL_NOTIFICATION_TITLE: 'Notification-wise Settings',
  LOCAL_NOTIFICATION_MSG:
    'Enable/Disable notification methods for specific notification types.',

  // otherDetails page
  ACHIEVEMENTS_PLACEHOLDER:
    'Awards, honours, recognition, participation in coding challenges like Hackathons etc.',
  ACADEMIC_EXCELLENCE_PLACEHOLDER:
    'Academic awards, honours at school/college etc.',
  PROJECTS_PLACEHOLDER:
    'Projects other than workplace projects: school/college/freelance projects etc.',
  HOBBIES_PLACEHOLDER:
    'Recreational/leisure activities like chess, reading, music, cooking etc.',
  PATENTS_PLACEHOLDER: 'Type, stage, date of patents filed…',
  OPEN_SOURCE_COMMUNITY_CONTRIBUTION_PLACEHOLDER:
    'Contribution to projects in open source environment…',
  LANGUAGES_PLACEHOLDER: 'Languages known: English, Hindi, Tamil, French etc.',
  // anomalyDetails warning dialog
  COPY_PASTE: 'Copy paste not allowed. This action will be reported.',
  FULLSCREEN: 'Exiting full screen not allowed. This action will be reported.',
  SWITCH_TAB: 'Switching tab not allowed. This action will be reported.',
  TEST_NOT_AVAILABLE: 'Test not available',
  TWO_PERSON: 'Two person visible',
  PERSON_MISSING: 'No person visible',
  ANOTHER_DEVICE: 'Another device visible',
  RIGHT_CLICK: 'Right Click not allowed. This action will be reported.',
  NONE: 'No anomaly',
  ACCOUNT_APPROVAL_PENDING: 'Account Approval Pending',
  ACCOUNT_INACTIVE: 'Account Inactive',
  ACCOUNT_REJECTED: 'Account Rejected',
  ASSESSMENT_LOADING: 'Your assessment is loading, please wait...',
  // download file
  ASSESSMENT_REPORT: 'assessmentreport.pdf',
  ASSESSMENT_DOWNLOAD_FAIL:
    'Report generation in progress. Please try after some time.',
  ASSESSMENT_DOWNLOAD_SUCCESSFUL: 'File downloaded successfully',
  PURCHASED_POINTS: 'Purchased Points',
  LOGIN_REGISTER: 'Login/Register',
  LINK_COPIED: 'Shareable link copied to clipboard',
  COPY_LINK_TOOLTIP: 'Click to copy the shareable link to clipboard',
  OPEN_TAB_TOOLTIP: 'Click to open the details in new tab',
  RETAKE: 'Retake',
  CAPTURE: 'Capture',
  PICUTRE: 'Picture',
  USE_CAMERA: 'Use Camera',
  PROFILE_HELPER_TEXT:
    'On AlignMyCareer, we require members to use their real identities, so take or upload a photo of yourself.',
  LATEST_EDUCATION:
    'Add educations in reverse chronological order with latest education first',
  LATEST_JOB: 'Add jobs in reverse chronological order with latest job first',
  PROFILE_PHOTO_HELPER_TEXT:
    'a photo gives authenticity to your profile and helps people recognize you.',
  PROFILE_PHOTO_INSTRUCTIONS:
    'Take or upload a photo of yourself. Align My Career requires members to use their real identities on the platform.',
  ID_CARD_HELPER_TEXT:
    'a photo identity increases the reliability of your profile.',
  ID_CARD_INSTRUCTIONS:
    'Align My Career requires members to use their real identities on the platform. Please take or upload a photo of government-approved identity card like Aadhar card, PAN card, Passport etc.',
  COMPANY_ID_CARD_HELPER_TEXT:
    'help us verify your association with your company.',
  COMPANY_ID_CARD_INSTRUCTIONS:
    'Please take or upload a photo of your current company ID card to confirm that you are part of the mentioned company. This is only for the purpose of verification and won’t be shared with anyone. ',
  ASSESSMENT_PICTURE_HELPER_TEXT:
    'a selfie with a photo ID gives a bona fide status to your test attempt.',
  ASSESSMENT_PICTURE_INSTRUCTIONS:
    'Take and upload a photo of yourself holding a photo identity card like Aadhar card, PAN card, VoterID card, Driving License etc. Your face and the identity card should be in the same frame. This is for verification of the candidate who is taking the assessment.',

  // ADMIN
  GENERATE_SITEMAP: 'Generate Sitemap',
  UPDATE_SKILLS: 'Update Skills',
  UPDATE_TECH: 'Update Technology',
  ACTIONS: 'Actions',
  ANALYTICS: 'Analytics',

  // ALT
  ALT_NO_RESULT_FOUND: 'No Matching record found',
  ALT_RE_ATTEMPT: 'Reattempt Assessments on Align My Career',
  ALT_JOB_CANDIDATES:
    'A cutting edge portal for job-seekers and recruiters that drastically reduces the time, effort, money, and resources needed',
  ALT_CAMERA: 'Remote Proctoring on Align My Career',
  ALT_CANDIDATE_PHOTO: 'Candidate Picture',
  ALT_JOB_LOGO: 'Post Jobs on Align My Career',
  ALT_ICON_UNLOCK:
    'Candidate profile preferred by Employers on Align My Career',
  ALT_ICON_INTERVIEW: 'Candidates interviewed by Employers  on Align My Career',
  ALT_ICON_ACCEPTED: 'Candidates Offered Job by Employers on Align My Career',
  ALT_ICON_JOBAPPLIED:
    'Candidates who have accepted Job Offers on Align My Career',
  ALT_ICON_HIRED: 'Candidates Hired by Employers on Align My Career',
  ALT_ICON_SHORTLISTED:
    'Candidates shortlisted by Employers on Align My Career',
  ALT_ICON_REJECTED:
    'Candidates who have rejected Job Offers on Align My Career',
  ALT_ICON_POSTED_JOB: 'Jobs posted by Employers on Align My Career',
  ALT_ICON_SEARCH_SEEN: 'Candidate Search Appearances on Align My Career',
  ALT_ICON_PROFILE_SEEN: 'Candidate Profile Views on Align My Career',
  ALT_ICON_ASSIGNMENT: 'Candidate taking Assessments on Align My Career',
  ALT_ICON_MATCHING_JOB: 'Matching jobs for Candidates on Align My Career',

  TITLE_ATTACHMENT: '| AlignMyCareer',
  TITLE_FINDJOBS: 'Search Jobs',
  TITLE_ALIGNMYCAREER:
    'AlignMyCareer - Cutting edge portal for job-seekers and recruiters that drastically reduces the time, effort, money, and resources needed',
  TITLE_FINDCANDIDATES: 'Search Candidates / Talent / Job Seekers',
  TITLE_EMPLOYER_PROFILE: 'Employer Profile',
  TITLE_POST_JOB: 'Free Job Posting',
  TITLE_POSTED_JOB: 'Posted Jobs',
  TITLE_MY_CANDIDATES: 'Preferred Candidates',
  TITLE_JOB_STATUS: 'AI Matched Candidates / Applied Candidates for job',
  TITLE_EMPLOYER_DETAILS: 'Employer Details',
  TITLE_JOB_DETAILS: 'Job Details',
  TITLE_CANDIDATE_DETAILS: 'Candidate Details',
  TITLE_CANDIDATE_PROFILE: 'Candidate Profile',
  TITLE_MY_JOBS: 'Preferred Jobs',
  TITLE_MY_PROFILE_ACTIVITY:
    'Applied Profile Activity / Auto Applied Profile Activity',
  TITLE_ASSESSMENT: 'Assessments - Technical, SoftSkills, Development',
  TITLE_SETTING: 'Settings - Notification and Preferences',
  TITLE_OFFERS: 'Offers - Cashbacks, Free Credit Points',
  TITLE_NOTIFICATIONS: 'Notifications - Get Real time updates',
  TITLE_ALL_OFFERS: 'All Offers - Cashbacks, Free Credit Points',
  TITLE_START_ASSESSMENT: 'Start Assignment',
  TITLE_UNIV_STUDENTS: 'University Student',
  TITLE_UPDATE_PASSWORD: 'Update Password',
  TITLE_PAYMENT: 'Purchase Credit Points',
  TITLE_SEO_FIND_JOBS: 'Find Jobs / Opportunities',
  TITLE_FIND_JOBS_SEARCHES: 'Find Jobs / Opportunities',
  TITLE_SEO_FIND_CANDIDATES: 'Find Candidates / Talent / Job Seekers',
  TITLE_FIND_CANDIDATES_SEARCHES: 'Find Candidates / Talent / Job Seekers',
  TITLE_UNSUBSCRIBE: 'Unsubscribe',
  TITLE_LOGIN: 'Login to unlock opportunities',
  TITLE_REGISTER: 'Free Register - Align My Career',
  TITLE_VERIFY_EMAIL: 'Verify Email',
  TITLE_CONFIRM_EMAIL: 'Confirm Email',
  TITLE_FORGOT_PASSWORD: 'Forgot Password',
  TITLE_RESEND_EMAIL: 'Resend Email',
  TITLE_CONFIRM: 'Confirm Registration',
  TITLE_CHANGE_PASSWORD: 'Change Password',
  TITLE_INFORMATION: 'Information',
  TITLE_ADMIN_ACTION: 'Admin Action',
  TITLE_ADMIN_ANALYTICS: 'Admin Analytics',
  TITLE_GUIDELINES: 'Assessment Guidelines',

  // Description
  DESC_DEFAULT:
    'Quick, guarantee-based solution to hiring requirements of companies, providing instant access to job-ready, productive candidates. The best platform for job-seekers to find best-matched jobs quickly, and to upgrade skill levels through assessments.',
  DESC_FINDJOBS: 'Search Jobs on Align My Career',
  DESC_FINDCANDIDATES:
    'Search Candidates / Talent / Job Seekers on Align My Career',
  DESC_EMPLOYER_PROFILE: 'Employer Profile on Align My Career',
  DESC_POST_JOB: 'Free Job Posting on Align My Career',
  DESC_POSTED_JOB: 'Posted Jobs',
  DESC_MY_CANDIDATES:
    'Candidates unlocked, shortlisted by employers on Align My Career',
  DESC_JOB_STATUS:
    'AI Matched Candidates / Applied Candidates for job on Align My Career',
  DESC_EMPLOYER_DETAILS: 'Employer Details',
  DESC_JOB_DETAILS: 'Job Details',
  DESC_CANDIDATE_DETAILS: 'Candidate Details',
  DESC_CANDIDATE_PROFILE: 'Candidate looking for job at Align My Career',
  DESC_MY_JOBS: 'Jobs shortlisted / applied by candidates on Align My Career',
  DESC_MY_PROFILE_ACTIVITY:
    'Activities done on candidate profiles by applying for jobs or directly by employers on Align My Career',
  DESC_ASSESSMENT:
    'Assessments - Technical, SoftSkills, Development on Align My Career',
  DESC_SETTING: 'Settings - Notification and Preferences on Align My Career',
  DESC_OFFERS: 'Offers - Cashbacks, Free Credit Points on Align My Career',
  DESC_NOTIFICATIONS:
    'Notifications - Get Real time updates on Align My Career',
  DESC_ALL_OFFERS:
    'All Offers - Cashbacks, Free Credit Points on Align My Career',
  DESC_START_ASSESSMENT: 'Start Assignment',
  DESC_UNIV_STUDENTS: 'University Student',
  DESC_UPDATE_PASSWORD: 'Update Password on Align My Career',
  DESC_PAYMENT: 'Purchase Credit Points on Align My Career',
  DESC_SEO_FIND_JOBS: 'Find Jobs / Opportunities on Align My Career',
  DESC_FIND_JOBS_SEARCHES: 'Find Jobs / Opportunities on Align My Career',
  DESC_SEO_FIND_CANDIDATES:
    'Find Candidates / Talent / Job Seekers on Align My Career',
  DESC_FIND_CANDIDATES_SEARCHES:
    'Find Candidates / Talent / Job Seekers on Align My Career',
  DESC_UNSUBSCRIBE: 'Unsubscribe from notifications on Align My Career',
  DESC_LOGIN: 'Login to unlock opportunities on Align My Career',
  DESC_REGISTER: 'Free Register - Align My Career',
  DESC_VERIFY_EMAIL: 'Verify Email on Align My Career',
  DESC_CONFIRM_EMAIL: 'Confirm Email on Align My Career',
  DESC_FORGOT_PASSWORD: 'Forgot Password on Align My Career',
  DESC_RESEND_EMAIL: 'Resend Email on Align My Career',
  DESC_CONFIRM: 'Confirm Registration on Align My Career',
  DESC_CHANGE_PASSWORD: 'Change Password on Align My Career',
  DESC_INFORMATION: 'Information',
  DESC_ADMIN_ACTION: 'Admin Action',
  DESC_ADMIN_ANALYTICS: 'Admin Analytics',
  DESC_GUIDELINES: 'Guidelines for taking assessments on Align My Career',
  // Job details dynamic title
  REMOTE_JOB: 'Remote Job',
  APPLYNOW: 'Apply Now',
  // Candidate details dynamic title
  CANDIDATE: 'Candidate',
  INTERNSHIP: 'Internship',
  YEAROFEXPERIENCE: 'year of experience',
  SUCCESS: 'Success',
  PATH: 'Path',
  MODE: 'Mode',
  BOTH: 'Both',
  JOB: 'Job',
  GENERATE_SKILLS: 'Generate Non-Verified Skills',
  GENERATE_COLLEGE: 'Generate Non-Verified Colleges',
  GENERATE_COMPANY: 'Generate Non-Verified Companies',
  DOMAIN: 'Domain',
  COMPANY_ID: 'Company ID',
  UPDATE_DOMAIN: 'Update Domain',
  TYPE: 'Type',
  PLEASE_SELECT_TYPE: 'Please Select a Type',
  POLICY_TYPE: 'Policy Type',
  CONDITION_TYPE: 'Condition Type',
  USE_TEMPLATE: 'Use Template',
  EXPIRY_DATE: 'Expiry Date',
  SHOW_DAYS: 'Show Days',
  DELETE_DAYS: 'Delete Days',
  BANNER: 'Banner',
  ANNOUNCEMENT: 'Announcement',
  DISMISS: 'Dismiss',
  STATE: 'State',
  OFFER_TYPE: 'Offer Type',
  CAND_REGISTRATION: 'CAND_REGISTRATION',
  CAND_FIRST_ASSESSMENT: 'CAND_FIRST_ASSESSMENT',
  ADMIN_AMOUNT: 'Amount/Point',
  ENTITY_ID: 'Entity ID',
  BANK_TRANSACTION_TIME: 'Bank Transaction Time',
  REFFRAL_ID: 'Referal ID',
  REFERRER: ' Referrer',
  CAND_REFER_CAND_REGISTRATION: 'CAND_REFER_CAND_REGISTRATION',
  CAND_REFER_CAND_FIRST_ASSESSMENT: 'CAND_REFER_CAND_FIRST_ASSESSMENT',
  EMP_REFER_CAND_REGISTRATION: 'EMP_REFER_CAND_REGISTRATION',
  EMP_REFER_CAND_FIRST_ASSESSMENT: 'EMP_REFER_CAND_FIRST_ASSESSMENT',
  CAND_REFER_EMP_POINTS_PURCHASE: 'CAND_REFER_EMP_POINTS_PURCHASE',
  SELF: 'Self',
  ADMIN_REJECTED: 'Rejected',
  OPTION: 'Option',
  TEXTFIELD: 'Textfield',
  CREATE: 'Create',
  UPLOAD_COLLEGE: 'Upload College',
  UPLOAD_QUESTIONS: 'Upload Questions',
  UPDATE_VERIFIED_COLLEGES: 'Update Verified Colleges',
  UPDATE_VERIFIED_COMPANIES: 'Update Verified Companies',
  UPLOAD_WL_DOMAINS: 'Upload WL Domains',
  UPLOAD_BL_DOMAINS: 'Upload BL Domains',
  UNIVERSITY_NAME: 'University Name',
  UNIVERSITY: 'University',
  EMPLOYER_ID: 'Employer ID',
  CONFIGURATION_ID: 'Configuration Id',
  WARRANTY_STATUS: 'Warranty Status',
  WARRANTY_APPROVED: 'WARRANTY APPROVED',
  WARRANTY_REJECTED: 'WARRANTY REJECTED',
  PROJECT_ID: 'Project ID',
  CANDIDATE_ID: 'Candidate ID',
  APPROVED: 'APPROVED',
  APPROVAL_PENDING: 'APPROVAL_PENDING',
  APPROVED_CHANGE: 'APPROVED_CHANGE',
  APPROVAL_REJECTED: 'REJECTED',
  CAPITAL_SUCCESS: 'SUCCESS',
  CAPITAL_REJECTED: 'REJECTED',
  NOTIFICATION: 'Notification JSON',
  NOTIFICATION_TEMPLATE: 'Notification Template JSON',
  CLICK_TO_ADD_SKILL: "Click '+' button to add skill",
  ADD_SKILL: "Click 'Add' button to add skill",
  UPDATE_SKILL: "Click 'Update' button to update skill",
  ASSESSMENTONAMC: 'Assessment on Align My Career',
  EMPLOYER_DETAILS_DESCRIPTION:
    'looking for candidates / job seekers on Align My Career',
  POSTED_BY: 'Jobs Posted by',
  ON_AMC: 'on Align My Career',
  REPORT: 'Report',
  REPORT_AMC: 'Report on Align My Career',
  I_UNDERSTAND: 'I Understand',
  PROCTOR_INSTRUCTIONS: 'Proctoring Instructions',
  UPLOAD_INDUSTRIES: 'Upload Industries',
  UPDATE_VERIFIED_INDUSTRIES: 'Update Verified Industries',
  GENERATE_NON_VERIFIED_INDUSTRIES: 'Generate Non-Verified Industries',
  UPDATE_INDUSTRY: 'Update Industry',
  DOMAIN_MAX_LIMIT_VALIDATION: 'Only 5 domains can be added',
  DOWNLOAD: 'Download',
  SHARE: 'Share',
  EXPLORE: 'Exploreeee',
};

export default UI;
